export const queryKeys = {
  listings: ['listings'] as const,
  listing: (id: string) => ['listing', id] as const,
  myListings: (userId: string) => ['my-listings', userId] as const,
  favorites: (userId: string) => ['favorites', userId] as const,
  conversations: (userId: string) => ['conversations', userId] as const,
  conversation: (id: string) => ['conversation', id] as const,
  messages: (conversationId: string) => ['messages', conversationId] as const,
  unreadMessages: (userId: string) => ['unread-messages', userId] as const,
  blockedUsers: (userId: string) => ['blocked-users', userId] as const,
  profile: (userId: string) => ['profile', userId] as const,
  reviews: (userId: string) => ['reviews', userId] as const,
  reviewSummary: (userId: string) => ['review-summary', userId] as const,
  pendingReviews: (userId: string) => ['pending-reviews', userId] as const,
  transactionByListing: (listingId: string) => ['transaction-by-listing', listingId] as const,
  transactionParticipants: (listingId: string) => ['transaction-participants', listingId] as const,
  mySupportCases: (userId: string) => ['my-support-cases', userId] as const,
  adminSupportCases: (view: string) => ['admin-support-cases', view] as const,
  notifications: (userId: string) => ['notifications', userId] as const,
  savedSearches: (userId: string) => ['saved-searches', userId] as const,
  marketplaceSearchAreas: ['marketplace-search-areas'] as const,
  marketplaceSearchPreference: (userId: string) => ['marketplace-search-preference', userId] as const,
  rescueDashboard: () => ['rescue-dashboard'] as const,
  rescueHub: (params: string) => ['rescue-hub', params] as const,
  publicRescueProfile: (ownerId: string) => ['public-rescue-profile', ownerId] as const,
};

export type QueryKey = readonly unknown[];
