packages:
  - marketing-site

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.9 || 57.0.10 || 57.0.14'
  - '@expo/metro-config@57.0.6 || 57.0.7 || 57.0.8'
  - '@expo/metro-runtime@57.0.6 || 57.0.7 || 57.0.9'
  - '@expo/prebuild-config@57.0.8 || 57.0.9 || 57.0.11'
  - expo-application@57.0.2
  - expo-asset@57.0.6 || 57.0.7 || 57.0.10
  - expo-constants@57.0.6 || 57.0.7 || 57.0.10
  - expo-modules-autolinking@57.0.8 || 57.0.9
  - expo-modules-core@57.0.6 || 57.0.7
  - expo-notifications@57.0.6 || 57.0.7 || 57.0.10
  - expo@57.0.7 || 57.0.8 || 57.0.12
  - '@expo/config-plugins@57.0.6'
  - '@expo/config@57.0.6'
  - '@expo/fingerprint@0.20.6 || 0.20.7'
  - '@expo/image-utils@0.11.4'
  - '@expo/require-utils@57.0.4'
  - '@expo/router-server@57.0.4'
  - babel-preset-expo@57.0.4
  - expo-modules-jsi@57.0.4
  - expo-splash-screen@57.0.5 || 57.0.6
  - expo-image-picker@57.0.6 || 57.0.9
  - '@expo/inline-modules@0.1.5'
  - '@expo/local-build-cache-provider@57.0.6'
  - expo-server@57.0.2
