packages:
  - marketing-site

allowBuilds:
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.9 || 57.0.10 || 57.0.14 || 57.0.16 || 57.0.17'
  - '@expo/metro-config@57.0.6 || 57.0.7 || 57.0.8 || 57.0.9'
  - '@expo/metro-runtime@57.0.6 || 57.0.7 || 57.0.9 || 57.0.11 || 57.0.12'
  - '@expo/prebuild-config@57.0.8 || 57.0.9 || 57.0.11 || 57.0.13'
  - expo-application@57.0.2
  - expo-asset@57.0.6 || 57.0.7 || 57.0.10 || 57.0.12 || 57.0.13
  - expo-constants@57.0.6 || 57.0.7 || 57.0.10 || 57.0.12 || 57.0.13
  - expo-modules-autolinking@57.0.8 || 57.0.9
  - expo-modules-core@57.0.6 || 57.0.7 || 57.0.12
  - expo-notifications@57.0.6 || 57.0.7 || 57.0.10 || 57.0.12 || 57.0.13
  - expo@57.0.7 || 57.0.8 || 57.0.12 || 57.0.14 || 57.0.15
  - '@expo/config-plugins@57.0.6'
  - '@expo/config@57.0.6 || 57.0.8'
  - '@expo/fingerprint@0.20.6 || 0.20.7 || 0.20.8 || 0.20.9'
  - '@expo/image-utils@0.11.4'
  - '@expo/require-utils@57.0.4'
  - '@expo/router-server@57.0.4 || 57.0.7'
  - babel-preset-expo@57.0.4
  - expo-modules-jsi@57.0.4 || 57.0.5
  - expo-splash-screen@57.0.5 || 57.0.6 || 57.0.7
  - expo-image-picker@57.0.6 || 57.0.9 || 57.0.11 || 57.0.12
  - '@expo/inline-modules@0.1.5 || 0.1.6'
  - '@expo/local-build-cache-provider@57.0.6 || 57.0.7'
  - expo-server@57.0.2
  - '@expo/log-box@57.0.3'
  - expo-location@57.0.11 || 57.0.12
  - expo-file-system@57.0.5
